<a href="https://colab.research.google.com/github/obdulia1/Aludenarticulo1/blob/master/02_Operaciones_Aritm%C3%A9ticas_y_de_Texto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://solariabiodata.com.mx/images/solaria_banner.png" width="400">

# Biodata Camp: Python
Bienvenidos al material que hemos preparado para el Biodata Camp: Python 🐍

# 02 Operaciones Aritméticas y de Texto


En Python existe una interfaz que nos permite hacer operaciones de manera interactiva. Esta funcionalidad se asemeja a la que usamos en una calculadora.

In [ ]:
"Hola mundo"

'Hola mundo'

![](https://i.kym-cdn.com/photos/images/original/000/462/037/349.jpg)

### Operadores aritméticos

Como es usual en lenguajes de programación, en Python, existen implementaciones generales de las operaciones aritméticas más relevantes. Cuando queremos indicarle una operación a Python lo hacemos a través de expresiones que indican a la computadora procesar valores a través de un operador:

In [ ]:
7+5

12

A continuación se describen los operadores que se pueden utilizar

| Operador | Significado |
|----------|-------------|
| `(` `)` | Paréntesis |
|  `**` | Potencia |
| `*` | Multiplicación |
| `/` | División |
| `//` | División entera |
| `%` | Módulo |
| `+` | Adición |
| `-` | Sustracción |





Vamos a practicar los operadores

In [ ]:
9*3

27

### Operadores binarios

Para la computadora los valores que nosotros percibimos como números (o caractéres) son definidos de forma binaria. En nuestro caso usamos el sitema de representación decimal, lo cual significa que tenemos 10 símbolos (`0`,`1`,`2`,`3`,`4`,`5`,`6`,`7`,`8`,`9`) para representar cualquier número, en el sistema binario solo existen el `0` y el `1`. Así, existe una representación binaria para todos los números. 

Una herramienta muy util es la conversión entre nuestro sistema de representación decimal al sistema de representación binaria. En teoría podriamos convertir cualquier tipo de representación a cualquier otra #cofcof**SistemaHexadecimal**#cofcof. Para ello nocesitaremos una operación mental:

- Primero necesitamos hacer una división de nuestro número decimal $D$ (*dividendo*) entre la base de nuestro sistema deseado (el *divisor* es $2$ porque vamos a convertir a binario):  $X=\frac{D}{2}$
- A continuación recolectamos el *residuo* $r$ y lo guardamos con la posición $i=1$, sabemos que el residuo solo puede ser `1` o `0` porque usamos $2$ como *divisor*
- Usaremos el resultado de la operación anterior $X$ para repetir nuevamente la operación, para fines prácticos cambiaremos $X$ por otra represantación: $D_{i+1}=\frac{D_{i}}{2}$ y repetiremos este procedimiento hasta mientras nuestro número $D$ sea mayor a $0$. $i$ representa la iteración del ciclo de operaciones, es decir, cada vez que completemos el ciclo aumentara en $1$ su valor, lo cual irá generando un orden en los residuos.
- Finalmente, uniremos todos los residuos $r_{i}$ pero en sentido inverso. Esa concatenación es la representación binaria de nuestro número original.




 #### Ejemplo conversión decimal a binario
Por ejemplo, hagamos la representación binaria del número `415`


In [ ]:
415//2

207

In [ ]:
415%2

1

El primer residuo es `1`, y el nuevo número *dividendo* es `207`, así que continuamos:



In [ ]:
207//2

103

In [ ]:
207%2

1

Ahora el residuo es `1` y el nuevo *dividendo* es `103`, por lo que nuestra serie de residuos es `1` `1`.

Y continuamos:

In [ ]:
103//2

51

In [ ]:
103%2

1

*dividendo* : `51`
serie de residuos :  `1` `1` `1`

In [ ]:
51//2

25

In [ ]:
51%2

1

*dividendo* : `25`
serie de residuos :  `1` `1` `1` `1`

In [ ]:
25//2

12

In [ ]:
25%2

1

*dividendo* : `12`
serie de residuos :  `1` `1` `1` `1`

In [ ]:
12//2

6

In [ ]:
12%2

0

*dividendo* : `6`
serie de residuos :  `1` `1` `1` `1` `0`

In [ ]:
6//2

3

In [ ]:
6%2

0

*dividendo* : `3`
serie de residuos :  `1` `1` `1` `1` `0` `0`

In [ ]:
3//2

1

In [ ]:
3%2

1

*dividendo* : `1`
serie de residuos :  `1` `1` `1` `1` `0` `0` `1`

In [ ]:
1//2

0

In [ ]:
1%2

1

*dividendo* : `0`
serie de residuos :  `1` `1` `1` `1` `0` `0` `1` `1`

En este punto ya tenemos al 0 como dividendo, por lo que terminamos el proceso invirtiendo el arreglo de residuos:

`1` `1` `0` `0` `1` `1` `1` `1`

Por lo que el número decimal `415` es representado en binario como `11001111`

 #### Operadores

Existen operaciones especiales que se pueden ejecutar usando operaciones a nivel binario. Cabe destacar que las operaciones binarias se ejecutan **mucho más rápido** que otras operaciones matemáticas, por lo que se pueden aprovechar su uso al analizar cantidades masivas de datos. Esto se debe a que se interpretan a nivel de procesador directamente.

A continuación una tabla con las operaciones binarias que pueden realizarse:

| Operador | Significado |
|----------|-------------|
| `>>` | Corrimiento binario a la derecha |
| `<<` | Corrimiento binario a la izquierda |
| `&` | AND |
| `\|` | OR |
| `^` | XOR |

Veamos como funcionan:

In [ ]:
3005//8

375

Los corrimientos basicamente funcionan como un atajo para multiplicar un número por $2^n$, los corrimientos a la izquierda utilizan $n$ positivos, los corrimientos a la derecha utilizann $n$ negativos. En otras palabras, corrimientos a la izquierda doblan los números, en cambio corrimientos a la derecha los parten por mitades.

Los operadores `AND`, `OR` y `XOR`  son compuertas lógicas que proceden del álgebra booleana. En este caso los `1` son interpretados como `verdadero` y los `0` como `falso`.

**`AND`**

| 6 | 5 || `6&5` = `4` |
|--|--||--|
| 1 | 1 || **1** |
| 1 | 0 || **0** |
| 0 | 1 || **0** |

**`OR`**

| 6 | 5 || `6\|5` = `7` |
|--|--||--|
| 1 | 1 || **1** |
| 1 | 0 || **1** |
| 0 | 1 || **1** |

**`XOR`**

| 6 | 5 || `6^5` = `3` |
|--|--||--|
| 1 | 1 || **0** |
| 1 | 0 || **1** |
| 0 | 1 || **1** |


In [ ]:
0^2

2

## Operadores de comparación

En computación siempre es útil hacer evaluaciones para comparar valores. A continuación se presentan operadores de comparación:

| Operador | Significado |
|----------|-------------|
| `==` | Igual que |
| `!=` | Diferente que |
| `>` | Mayor que |
| `>=` | Mayor o igual que |
| `<` | Menor que |
| `<=` | Menor o igual que |

Es importante destacar que estas comparaciones generan resultados del tipo lógico, es decir valores para un resultado verdadero que en pyhton se asiga **`True`** y falso representado como **`False`**.


In [ ]:
4==4

True

##Precedencia de operadores

Es importantísimo asignar un orden de ejecución cuando se combinan operadores aritméticos en computación.


| Prioridad | Operador | Significado |
|-----------|----------|-------------|
| 1 | `(` `)` | Paréntesis |
| 2 |  `**` | Potencia |
| 3* | `+x`, `-x`, `~x` | Adición unitaria, sustracción unitaria, NOT binario |
| 4 |  `*`, `/`, `//`, `%` | Multiplicación, división, división entera y módulo |
| 5 | `+`, `-` | Adición, sustracción |
| 6 | `>>`, `<<` | Corrimientos binarios |
| 7 | `&` | AND binario |
| 8 | `\|` | OR binario |
| 9 | `^` | XOR binario |
| 10 | `==`, `!=`, `>`, `>=`, `<`, `<=`, `is`, `is not`, `in`, `not in` | Comparaciones y operadores de pertenencia |
| 11 | `not` | NOT lógico |
| 12 | `and`| AND lógico |
| 13 | `or` | OR lógico |

A continuación vamos a visualizar este comportamiento:

In [ ]:
(2+4)*3**2

54

##Operadores de texto

Así como se pueden procesar valores númericos y lógicos, en Python también se pueden procesar valores de texto que contienen caracteres.

A continuación se presenta una tabla de los operadores de texto

| Operador | Significado |
|--|--|
| `+` | Concatenación |
| `*` | Repetición |
| `[]` | Selección de caracter |
| `[:]` | Selección de rango de caracteres |
| `in` | Está contenido en |
| `not in` | No está contenido en |
| `%` | Realizar formateo especial* |

**Formateo especial (`%`)**

| Caracter | Descripción |
|--|--|
| `%c` | Caracter |
| `%s` | Conversión por cadena |
| `%i` | Conversión por entero |
| `%o` | Conversión por octal |
| `%x` | Conversión por hexadecimal |
| `%e` | Formato con notación exponencial |
| `%f` | Formato con punto decimal |




Por ejemplo:

In [ ]:
"Hola %f, que tal"%(12-57)

'Hola -45.000000, que tal'

![](https://media1.tenor.com/images/7105b08d72125255d179989d7ce8bf22/tenor.gif)